package docker

import (
	"bufio"
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"sync"
)

const nginxConfigPath = "/etc/nginx/conf.d/dynamic_subdomains.conf"
const nginxTempPath = "/etc/nginx/conf.d/dynamic_subdomains.conf.tmp"
const baseDomain = "klouds.online"

// NginxManager handles dynamic subdomain routing for Nginx via a map configuration.
type NginxManager struct {
	mu sync.Mutex
}

var globalNginxManager = &NginxManager{}

// SyncNginx reconstructs the entire Nginx map configuration from active containers.
func SyncNginx(dockClient *Client) error {
	return globalNginxManager.SyncNginx(dockClient)
}

// AddNginxMapping atomically adds or updates a subdomain-to-port mapping.
func AddNginxMapping(subdomain string, port uint16) error {
	return globalNginxManager.AddMapping(subdomain, port)
}

// RemoveNginxMapping atomically removes a subdomain mapping.
func RemoveNginxMapping(subdomain string) error {
	return globalNginxManager.RemoveMapping(subdomain)
}

// AddMapping updates the map configuration file with a new domain-port pair.
func (m *NginxManager) AddMapping(subdomain string, port uint16) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	mappings, err := m.readMappings()
	if err != nil {
		return err
	}

	mappings[subdomain] = fmt.Sprintf("%d", port)

	return m.writeMappingsAndReload(mappings)
}

// RemoveMapping removes a domain from the map configuration file.
func (m *NginxManager) RemoveMapping(subdomain string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	mappings, err := m.readMappings()
	if err != nil {
		return err
	}

	delete(mappings, subdomain)

	return m.writeMappingsAndReload(mappings)
}

// SyncNginx reads all active DevPanel containers and rewrites the Nginx map.
func (m *NginxManager) SyncNginx(dockClient *Client) error {
	ctx := context.Background()
	containers, err := dockClient.ListContainers(ctx)
	if err != nil {
		return fmt.Errorf("failed to list containers for nginx sync: %w", err)
	}

	mappings := make(map[string]string)

	for _, c := range containers {
		cName := ""
		if len(c.Names) > 0 {
			cName = strings.TrimPrefix(c.Names[0], "/")
		}

		if !strings.HasPrefix(cName, "devpnl-") {
			continue
		}

		if c.State != "running" || len(c.Ports) == 0 {
			continue
		}

		var pubPort uint16
		for _, p := range c.Ports {
			if p.PublicPort > 0 {
				pubPort = p.PublicPort
				break
			}
		}

		if pubPort == 0 {
			continue
		}

		parts := strings.Split(cName, "-")
		if len(parts) < 3 {
			continue
		}

		projectSlug := parts[1]
		domain := fmt.Sprintf("%s.%s", projectSlug, baseDomain)
		mappings[domain] = fmt.Sprintf("%d", pubPort)
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	return m.writeMappingsAndReload(mappings)
}

// readMappings reads the current Nginx map configuration from disk.
func (m *NginxManager) readMappings() (map[string]string, error) {
	mappings := make(map[string]string)
	
	f, err := os.Open(nginxConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return mappings, nil
		}
		return nil, fmt.Errorf("failed to open nginx config: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		
		// Expected format: app1.klouds.online 8081;
		line = strings.TrimSuffix(line, ";")
		parts := strings.Fields(line)
		if len(parts) == 2 {
			mappings[parts[0]] = parts[1]
		}
	}
	
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read nginx config: %w", err)
	}
	
	return mappings, nil
}

// writeMappingsAndReload performs the atomic write and executes Nginx reload.
func (m *NginxManager) writeMappingsAndReload(mappings map[string]string) error {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by DevPanel. Do not edit manually.\n")
	sb.WriteString("# Map format: $host $app_port;\n\n")

	for domain, port := range mappings {
		sb.WriteString(fmt.Sprintf("%s %s;\n", domain, port))
	}

	// 1. Write to a temporary file
	err := os.WriteFile(nginxTempPath, []byte(sb.String()), 0644)
	if err != nil {
		return fmt.Errorf("failed to write nginx temp config: %w", err)
	}

	// 2. Atomically rename the temporary file over the actual file
	err = os.Rename(nginxTempPath, nginxConfigPath)
	if err != nil {
		return fmt.Errorf("failed to atomically rename nginx config: %w", err)
	}

	// 3. Execute Nginx reload using sudo (passwordless sudo must be configured for the ubuntu user)
	cmd := exec.Command("sudo", "nginx", "-s", "reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to reload nginx: %v, output: %s", err, string(output))
	}

	log.Printf("nginx_manager: successfully synced %d mappings and reloaded Nginx", len(mappings))
	return nil
}
