package docker

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"sync"
)

const nginxConfigPath = "/etc/nginx/conf.d/dynamic_subdomains.conf"
const nginxTempPath = "/etc/nginx/conf.d/dynamic_subdomains.conf.tmp"
const baseDomain = "klouds.online"

// NginxManager handles dynamic subdomain routing for Nginx.
type NginxManager struct {
	mu     sync.Mutex
	routes map[string]int // maps subdomain -> internal port
}

var globalNginxManager = &NginxManager{
	routes: make(map[string]int),
}

// AddRoute adds a new subdomain route and reloads Nginx.
// The subdomain parameter should just be the prefix (e.g. "project-1").
func (m *NginxManager) AddRoute(subdomain string, port int) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	fullDomain := fmt.Sprintf("%s.%s", subdomain, baseDomain)
	m.routes[fullDomain] = port

	return m.syncConfig()
}

// RemoveRoute removes a subdomain route and reloads Nginx.
func (m *NginxManager) RemoveRoute(subdomain string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	fullDomain := fmt.Sprintf("%s.%s", subdomain, baseDomain)
	delete(m.routes, fullDomain)

	return m.syncConfig()
}

// syncConfig writes the Nginx configuration to disk atomically and reloads Nginx.
// The caller must hold the mutex.
func (m *NginxManager) syncConfig() error {
	var sb strings.Builder

	sb.WriteString("# Auto-generated by DevPanel. Do not edit manually.\n\n")

	for domain, port := range m.routes {
		configBlock := fmt.Sprintf(`server {
    listen 80;
    server_name %s;

    location / {
        proxy_pass http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

`, domain, port)
		sb.WriteString(configBlock)
	}

	// Write to temporary file first
	err := os.WriteFile(nginxTempPath, []byte(sb.String()), 0644)
	if err != nil {
		return fmt.Errorf("failed to write nginx temp config: %w", err)
	}

	// Atomically rename temp file to actual config path
	err = os.Rename(nginxTempPath, nginxConfigPath)
	if err != nil {
		return fmt.Errorf("failed to rename nginx config: %w", err)
	}

	// Reload Nginx using sudo
	cmd := exec.Command("sudo", "nginx", "-s", "reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to reload nginx: %v, output: %s", err, string(output))
	}

	log.Printf("nginx_manager: successfully synced %d routes and reloaded Nginx", len(m.routes))
	return nil
}
