package docker

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"sync"
)

const nginxConfigPath = "/etc/nginx/conf.d/dynamic_subdomains.conf"
const nginxTempPath = "/etc/nginx/conf.d/dynamic_subdomains.conf.tmp"
const baseDomain = "klouds.online"

// NginxManager handles dynamic subdomain routing for Nginx.
type NginxManager struct {
	mu sync.Mutex
}

var globalNginxManager = &NginxManager{}

// SyncNginx is the package-level exported function to trigger an Nginx config rewrite.
func SyncNginx(dockClient *Client) error {
	return globalNginxManager.SyncNginx(dockClient)
}

// SyncNginx reads all active DevPanel containers and rewrites the Nginx configuration.
func (m *NginxManager) SyncNginx(dockClient *Client) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	ctx := context.Background()
	containers, err := dockClient.ListContainers(ctx)
	if err != nil {
		return fmt.Errorf("failed to list containers for nginx sync: %w", err)
	}

	type projectPorts struct {
		FrontendPort uint16
		BackendPort  uint16
	}

	projects := make(map[string]*projectPorts)

	for _, c := range containers {
		cName := ""
		if len(c.Names) > 0 {
			cName = strings.TrimPrefix(c.Names[0], "/")
		}

		if !strings.HasPrefix(cName, "devpnl-") {
			continue
		}

		if c.State != "running" || len(c.Ports) == 0 {
			continue
		}

		var pubPort uint16
		for _, p := range c.Ports {
			if p.PublicPort > 0 {
				pubPort = p.PublicPort
				break
			}
		}

		if pubPort == 0 {
			continue
		}

		parts := strings.Split(cName, "-")
		if len(parts) < 3 { // devpnl-project-service
			continue
		}
		
		projectSlug := parts[1]
		
		if projects[projectSlug] == nil {
			projects[projectSlug] = &projectPorts{}
		}

		svcType := c.Labels["devpanel.service.type"]
		lowerName := strings.ToLower(cName)

		// Determine if container is a web/frontend or an api/backend
		isApi := false
		if svcType == "api" || svcType == "backend" || strings.Contains(lowerName, "api") || strings.Contains(lowerName, "backend") {
			isApi = true
		}

		isWeb := false
		if svcType == "web" || svcType == "static" || svcType == "frontend" || strings.HasSuffix(lowerName, "-web") || strings.Contains(lowerName, "-ui") || strings.Contains(lowerName, "app") {
			isWeb = true
		}

		// Assignment logic
		if isApi {
			projects[projectSlug].BackendPort = pubPort
		} else if isWeb {
			projects[projectSlug].FrontendPort = pubPort
		} else {
			// If we don't know, just assume it's frontend for now (if not already set)
			if projects[projectSlug].FrontendPort == 0 {
				projects[projectSlug].FrontendPort = pubPort
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("# Auto-generated by DevPanel. Do not edit manually.\n\n")

	for projectSlug, ports := range projects {
		domain := fmt.Sprintf("%s.%s", projectSlug, baseDomain)

		sb.WriteString(fmt.Sprintf("server {\n    listen 80;\n    server_name %s;\n\n", domain))
		
		if ports.BackendPort > 0 {
			sb.WriteString(fmt.Sprintf(`    location /api/ {
        proxy_pass http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

`, ports.BackendPort))
		}

		if ports.FrontendPort > 0 {
			sb.WriteString(fmt.Sprintf(`    location / {
        proxy_pass http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
`, ports.FrontendPort))
		}

		sb.WriteString("}\n\n")
	}

	// Write to temporary file first
	err = os.WriteFile(nginxTempPath, []byte(sb.String()), 0644)
	if err != nil {
		return fmt.Errorf("failed to write nginx temp config: %w", err)
	}

	// Atomically rename temp file to actual config path
	err = os.Rename(nginxTempPath, nginxConfigPath)
	if err != nil {
		return fmt.Errorf("failed to rename nginx config: %w", err)
	}

	// Reload Nginx using sudo
	cmd := exec.Command("sudo", "nginx", "-s", "reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to reload nginx: %v, output: %s", err, string(output))
	}

	log.Printf("nginx_manager: successfully synced %d projects and reloaded Nginx", len(projects))
	return nil
}
